# Generated by Django 5.1.6 on 2025-03-05 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='locked',
            field=models.BooleanField(default=False),
        ),
    ]
