# Generated by Django 5.1.6 on 2025-03-05 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_locked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[('Owner', 'Owner'), ('Admin', 'Admin'), ('Staff', 'Staff')], default='Staff'),
        ),
    ]
