# Generated by Django 5.1.6 on 2025-03-07 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plinger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('whatsapp_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('telegram_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('plingme_by', models.JSONField(default=list)),
                ('plingme_when', models.JSONField(default=list)),
                ('plingme_freq', models.CharField(choices=[('once', 'Solo una vez'), ('weekly', 'Semanal'), ('monthly', 'Mensual'), ('custom', 'Personalizado')], default='once', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('email__isnull', False), ('phone__isnull', False), _connector='OR'), name='require_email_or_phone')],
            },
        ),
    ]
