# Generated by Django 5.1.6 on 2025-03-08 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('plingers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plinger',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='plingers', to='company.company'),
            preserve_default=False,
        ),
    ]
