# Generated by Django 5.1.6 on 2025-03-10 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plingers', '0002_plinger_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plinger',
            name='plingme_freq',
            field=models.CharField(choices=[('once', 'Only Once'), ('weekly', 'Weekly'), ('monthly', 'Montly'), ('custom', 'Custom')], default='once', max_length=20),
        ),
    ]
